#!/bin/bash

echo "Running git pre-commit hook"
git stash -q --keep-index
./gradlew clean build
RESULT=$?
git stash pop -q

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0



